[package]
name = "npaperbot-telegram"
version = "2.0.0"
authors = ["Alexander Zaitsev <zamazan4ik@tut.by>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
futures = "0.3.5"
lazy_static = "1.4.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"
regex = "1.3.9"
reqwest = "0.10.6"
serde_json = "1.0.55"
teloxide = "0.3.1"
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }

[profile.release]
lto = true