FROM rust:1.45.2-slim as builder
WORKDIR /usr/src/npaperbot-telegram
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates
COPY --from=builder /usr/local/cargo/bin/npaperbot-telegram /usr/local/bin/npaperbot-telegram
CMD ["npaperbot-telegram"]