FROM docker.io/rust:1.64.0 as builder
WORKDIR /usr/src/npaperbot-telegram
COPY . .
RUN cargo install --path .

FROM docker.io/debian:bullseye-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/npaperbot-telegram /usr/local/bin/npaperbot-telegram
CMD ["npaperbot-telegram"]
