FROM rust:1.45.2 as builder
WORKDIR /usr/src/npaperbot-telegram
ARG NPAPERBOT_SOURCE_URL=https://github.com/ZaMaZaN4iK/npaperbot-telegram.git
RUN git clone ${NPAPERBOT_SOURCE_URL}
WORKDIR npaperbot-telegram
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates
COPY --from=builder /usr/local/cargo/bin/npaperbot-telegram /usr/local/bin/npaperbot-telegram
CMD ["npaperbot-telegram"]