FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG NPAPERBOT_VERSION=1.0.3

ARG NPAPERBOT_SOURCE_URL=https://github.com/ZaMaZaN4iK/npaperbot-telegram/archive/v${NPAPERBOT_VERSION}.zip

RUN dnf install -y perl autoconf automake libtool wget unzip clang cmake make python3-pip \
    && pip install conan

WORKDIR /usr/src/npaperbot-telegram

RUN wget ${NPAPERBOT_SOURCE_URL} && unzip v${NPAPERBOT_VERSION}.zip

WORKDIR npaperbot-telegram-${NPAPERBOT_VERSION}

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/npaperbot-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/npaperbot_telegram"]

