FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG NPAPERBOT_SOURCE_URL=https://github.com/ZaMaZaN4iK/npaperbot-telegram.git

RUN dnf install -y perl autoconf automake libtool clang cmake make git python3-pip \
    && pip install conan

WORKDIR /usr/src/npaperbot-telegram

RUN git clone ${NPAPERBOT_SOURCE_URL}

WORKDIR npaperbot-telegram

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/npaperbot-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/npaperbot_telegram"]

